# aula 4

In [4]:
import numpy as np

In [5]:
vetor = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

vetor2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [6]:
#posições
print(vetor[0])

print(vetor[0:2])

print(vetor[-1])

print(vetor2d[2][0])
print(vetor2d[0][1])

1
[1 2]
9
7
2


In [7]:
#filtrando dados

maior_que_5 = vetor[vetor > 5]

somente_par = vetor[vetor % 2 ==0 ]

igual_a_5 = vetor[vetor == 5]

maior_que_3_menor_que_8 = vetor[(vetor > 3)&(vetor < 8)]


print(maior_que_5)
print(somente_par)
print(igual_a_5)
print(maior_que_3_menor_que_8)

[6 7 8 9]
[2 4 6 8]
[5]
[4 5 6 7]


# Exercício

* Exercício 33: Faça um programa que gere um vetor de retornos positivos ou negativos entre -1 e 1 na quantidade de dias que o usuário escolher. Devolva um vetor dos retornos positivos, o primeiro e o último retorno.

In [19]:
lista_de_retornos = int(input("quantos retornos irão ter"))

lista = []

numero_sortido = np.random.uniform(-1,1,(lista_de_retornos))
lista = np.array(numero_sortido)


print(lista)
print(lista[lista > 0])
print(lista[0],lista[-1])

[-0.97538297  0.61298863  0.86337004 -0.25144418]
[0.61298863 0.86337004]
-0.9753829674602048 -0.25144417833842225
