### Primeira aula Numpy

In [2]:
import numpy as np

In [3]:
#criar um array

lista = [1,2,3,4]

tupla = (1,2,3,4)

array_a_partir_de_lista = np.array(lista)
array_a_partir_de_tupla = np.array(tupla)

array_a_partir_de_lista

array([1, 2, 3, 4])

In [4]:
#usando um range 

array_simples = np.arange(10)

array_sequencial = np.arange(10,100,10)

array_simples,array_sequencial

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [5]:
#criando arrays de zeros ou ums

vetor_zero = np.zeros(5)

vetor_um = np.ones(5)

vetor_zero, vetor_um

(array([0., 0., 0., 0., 0.]), array([1., 1., 1., 1., 1.]))

In [12]:
#criando vetores aleatorios

vetor_aleatorio_entre_0_1 = np.random.rand(3,2)
vetor_aleatorio_inteiro = np.random.randint(low = 0, high = 10 , size = 3)
vetor_aleatorio_com_negativos = np.random.uniform(-2,2,3)


print(vetor_aleatorio_entre_0_1)
print(vetor_aleatorio_inteiro)
print(vetor_aleatorio_com_negativos)




[[0.38465807 0.9288602 ]
 [0.7098293  0.73909205]
 [0.89726866 0.11654698]]
[2 0 6]
[ 0.49062601 -0.6960044  -1.30949267]


In [13]:
#criando arrays bi ou tridimensionais

lista1 = [1,2,3]
lista2 = [4,5,6]
lista3 = [7,8,9]

array2d = np.array([lista1,lista2])

array3d = np. array([lista1,lista2,lista3])

array2d,array3d

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [14]:
#criando matrizes

matriz = np. matrix([[20,30],[90,80]])

matriz

matrix([[20, 30],
        [90, 80]])

In [15]:
#listas x numpy

lista_1 = [1,1,1,1]
lista_2 = [1,1,1,1]


print(lista_1 + lista_2)
print(np.array(lista_1) + np.array(lista_2))


[1, 1, 1, 1, 1, 1, 1, 1]
[2 2 2 2]


In [21]:
#teste lista x numpy

import timeit


#listas

tempo_listas = timeit.timeit('''X= range(1000); Y = range(1000); [X[i] + Y[i] for i in range(len(X))]''',number = 100)

tempo_vetor = timeit.timeit('''X= np.arange(1000); Y = np.arange(1000); X + Y ''',number = 100,setup="import numpy as np")


print(tempo_listas, tempo_vetor)
print(f"os vetorores sao{tempo_listas/tempo_vetor} vezes mais rapidos.")

0.010131900082342327 0.000741399941034615
os vetorores sao13.665903544857823 vezes mais rapidos.


# Exercícios

* Exercício 30: Peça pro usuário inputar a cotação de 3 ações. Crie um array de cotações.
* Exercício 31: Peça pro usuário digitar dois números no programa e crie um arrange sequencial entre esse números.
* Exercício 32: Crie um programa que gere numeros aleatórios inteiros entre 0 e 60 e devolva 6 números da mega sena pro usuário. Depois, exiba uma probabilidade aleatória de o usuário sair vencedor. Garanta que sejam 6 números diferentes!

In [38]:
#exercício 30

print("Me diga 3 Ações")

Ação_1 = input("1º ação")
Ação_2 = input("2º ação")
Ação_3 = input("3º ação")

array_cotação = np.array([Ação_1,Ação_2,Ação_3])
print(array_cotação)


Me diga 3 Ações
['10' '20' '30']


In [36]:
#exercio 31
inicio = input("digite um numero qualquer para iniciar o loop")
fim = input("digite um numerr para terminar o loop")

resultado = np.arange(float(inicio),float(fim),2)

print(resultado)

[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 181 183 185 187 189 191 193 195 197 199 201 203 205 207 209 211 213 215
 217 219 221 223 225 227 229 231 233 235 237 239 241 243 245 247 249 251
 253 255 257 259 261 263 265 267 269 271 273 275 277 279 281 283 285 287
 289 291 293 295 297 299 301 303 305 307 309 311 313 315 317 319 321 323
 325 327 329 331 333 335 337 339 341 343 345 347 349 351 353 355 357 359
 361 363 365 367 369 371 373 375 377 379 381 383 385 387 389 391 393 395
 397 399 401 403 405 407 409 411 413 415 417 419 421 423 425 427 429 431
 433 435 437 439 441 443 445 447 449 451 453 455 457 459 461 463 465 467
 469 471 473 475 477 479 481 483 485 487 489 491 49

In [39]:
#exercio 32 
numeros_aleatorios= []

numeros_aleatorios.append(np.random.randint(low = 0, high = 60,size = 1)[0])

while len(numeros_aleatorios)<6:
    mega_sena = np.random.randint(0,60,1)

    if mega_sena not in numeros_aleatorios:
        numeros_aleatorios.append(mega_sena[0])

probabilidade = np.random.uniform(0,1)

print(f"numeros sorteados{numeros_aleatorios}")
print(f"probabilidade {probabilidade}")

numeros sorteados[8, 40, 23, 14, 34, 48]
probabilidade 0.7875632130446723
