# Mundo 5

In [2]:
import numpy as np

In [3]:
#Juntar dois Arrays

array1 = np.arange(20,25)
array2 = np.arange(15)

array_completo = np.concatenate([array1,array2])


print(array_completo)

[20 21 22 23 24  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [4]:
#Separando em dois Arrays

array_separado1,array_separado2 = np.split(array_completo,[5])

print(array_separado1)
print(array_separado2)

[20 21 22 23 24]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [5]:
#colocar novos dados em um array 

array_completo = np.append(array_completo,2000)

print(array_completo)

array_completo = np.insert(array_completo,3,3000)

print(array_completo)



[  20   21   22   23   24    0    1    2    3    4    5    6    7    8
    9   10   11   12   13   14 2000]
[  20   21   22 3000   23   24    0    1    2    3    4    5    6    7
    8    9   10   11   12   13   14 2000]


In [13]:
#deletar dados do array

array_completo = np.delete(array_completo,-1)

print(array_completo)

[  20   21   22 3000   23   24    0    1    2    3    4    5    6    7
    8    9   10   11   12   13   14]


In [12]:
# reshape

array_3x3 = np.arange(9).reshape(3,3)# util para fazer regressão linear

print(array_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
#trocando numeros dentro de uma condição
array_inicial = np.array([4, 4, 4, 4, 7, 6, 5, 32, 13, 2, 32, 675, 74, 465])

#como trocar todos os numeros menos que 40 por 0

array_booleano = (array_inicial < 40)
print(array_booleano)

array_inicial[array_booleano] = 0

print(array_inicial)


[ True  True  True  True  True  True  True  True  True  True  True False
 False False]
[  0   0   0   0   0   0   0   0   0   0   0 675  74 465]


In [15]:
#ordenar objetos dentro de uma lista

array_desordenado = np.array([23109, 2349, 349, 20, 3, 5, 12490])

array_crescente = np.sort(array_desordenado)

array_decrescente = -np.sort(-array_desordenado)

print(array_crescente, array_decrescente)

[    3     5    20   349  2349 12490 23109] [23109 12490  2349   349    20     5     3]


# Exercício

* Exercício 34: Peça ao usuário digitar o lucro da Petrobras, Vale e Weg. Mostre os lucros em ordem do maior pro menor. (Utilize arrays e ferramentas como append, np.sort, etc)

In [17]:
#exercio 34

lucro_petro = float(input("Digite o lucro da Petrobras"))
lucro_vale = float(input("Digite o lucro da Vale"))
lucro_weg = float(input("Digite o lucro da Weg"))

lucros = np.array([lucro_petro,lucro_vale,lucro_weg])

lucros_crescente = -np.sort(-lucros)

lucros_juntas = np.array([(lucro_petro + lucro_vale + lucro_weg)])

print(f"Lucro crescente{lucros_crescente}, Lucros juntas{lucros_juntas}")

Lucro crescente[10. 20. 30.], Lucros juntas[60.]


In [18]:
#outra forma de resolver porem com mais sofisticação

empresas = np.array(["Petrobras","Vale","Petrobras"])

array_lucros = np.array([])

for empresa in empresas:
    lucro = float(input(f"Digite o Lucro da {empresa}: "))
    array_lucros = np.append(array_lucros,lucro)

array_lucros = -np.sort(-array_lucros)

print(f"Lucro das empresas, do maior para menor:{array_lucros}")

Lucro das empresas, do maior para menor:[30. 20. 10.]
