# Aula 6

In [1]:
import numpy as np

In [4]:
#Todas as operações funcionam com os vetores

array1 = np.array([1, 1, 1, 1])
array2 = np.array([4, 2, 6, 2])
array3 = np.array([2, 2])


lista_normal = [1,1,1,1]
lista_normal2 = [4,2,6,2]

print(array1 + array2)
print(lista_normal + lista_normal2)

[5 3 7 3]
[1, 1, 1, 1, 4, 2, 6, 2]


In [6]:
#E se eu quiser somar um número só?

soma_a_todos_os_elementos = np.array([1,1,1,1]) + 20

print(soma_a_todos_os_elementos)

[21 21 21 21]


In [8]:
#Todas as operações funcionam normal
subtração = array1 - array2
divisao = array1/array2
multiplicacao = array1 * array2
exponenciacao = array1 ** array2

print(subtração)
print(divisao)
print(multiplicacao)
print(exponenciacao)

[-3 -1 -5 -1]
[0.25       0.5        0.16666667 0.5       ]
[4 2 6 2]
[1 1 1 1]


In [9]:
#operaçoes dentro do vetor
vetor = np.array([1,4,-4,-1,2])

print(vetor)
print(vetor.sum())
print(vetor.max())
print(vetor.min())
print(np.abs(vetor))


[ 1  4 -4 -1  2]
2
4
-4
[1 4 4 1 2]


In [10]:
#Estatisticas descritivas

vetor = np.array([1, 20, -4, -12, 2000])

media = np.mean(vetor)
mediana = np.median(vetor)
desvio_p = np.std(vetor)
var = np.var(vetor)

print(media)#media
print(mediana)#mediana
print(desvio_p)#desvio padrão
print(var)#variancia



401.0
1.0
799.56938410622
639311.2


In [11]:
#matriz de correlação

vetor2 = np.array([5, 4, 3, -5, 4])
vetor3 = np.array([2, 6, 7, -5, 1])

print(np.corrcoef((vetor,vetor2,vetor3)))


[[ 1.          0.25471058 -0.13247913]
 [ 0.25471058  1.          0.76783876]
 [-0.13247913  0.76783876  1.        ]]


# Exercício

* Exercício 35: Faça um programa que o usuário digite a rentabilidade de ações, com quantas ações o usuário quiser. Transforme essas listas em arrays e devolva pro usuário:

        A média de rentabilidade da carteira.
        O Desvio padrão da carteira.
        A mediana de retornos da carteira.
        O maior retorno.
        O menor retorno.

In [24]:
#exercicio 
Carteira_acoes = np.array([])
print("Bom Dia, Vamos fazer a analise da carteira")
resposta = input("Gostaria de fazer uma consulta [S/N]?")

while resposta != "N" or resposta != "n":
    if resposta == "S" or resposta == "s":
        rentabilidade = float(input("Digite a rentabilidade da Ação"))
        Carteira_acoes= np.append(Carteira_acoes,rentabilidade)
    elif resposta == "N" or resposta == "n":
        break
    else:
        print("Não entedi pode repetir")

    resposta = input("Gostaria de fazer um novo registro [S/N]?")
    
media_carteira = np.mean(Carteira_acoes)
desvio_carteira = np.std(Carteira_acoes)
mediana_carteira = np.median(Carteira_acoes)
maior_retorno = Carteira_acoes.max()
menor_retorno = Carteira_acoes.min()


print(f"A média de rentabilidade da carteira : {media_carteira}")
print(f"O Desvio padrão da carteira: {desvio_carteira}")
print(f"A mediana de retornos da carteira: {mediana_carteira}")
print(f"O maior retorno: {maior_retorno}")
print(f"O menor retorno:{menor_retorno}")

Bom Dia, Vamos fazer a analise da carteira
A média de rentabilidade da carteira : 10.0
O Desvio padrão da carteira: 0.0
A mediana de retornos da carteira: 10.0
O maior retorno: 10.0
O menor retorno:10.0
